In [ ]:
import pandas as pd

df: pd.DataFrame = pd.read_csv("../data/student_performance_data.csv")
df.head()

   student_id  gender  study_hours_per_day  ...  sleep_hours  overall_score  grade
0      100000    Male                 4.54  ...         8.09        52.3480      D
1      100001  Female                 5.26  ...         4.73        53.9485      D
2      100002    Male                 8.69  ...         8.73        82.0375      B
3      100003    Male                 4.06  ...         8.22        66.4110      C
4      100004    Male                 8.83  ...         8.59        65.6005      C

[5 rows x 14 columns]

## ubah nama kolom

In [102]:
df: dict = df.rename(columns={
    'student_id': 'id_siswa',
    'gender': 'jenis_kelamin',
    'study_hours_per_day': 'jam_belajar_per_hari',
    'attendance_percentage': 'presentase_kehadiran',
    'assignment_score': 'nilai_tugas',
    'midterm_score': 'nilai_UTS',
    'final_exam_score': 'nilai_UAS',
    'participation_score': 'nilai_partisipasi',
    'internet_access': 'akses_internet',
    'extra_classes': 'kelas_tambahan',
    'parent_education': 'pendidikan_orang_tua',
    'sleep_hours': 'jam_tidur',
    'overall_score': 'nilai_keseluruhan',
    'grade': 'nilai'
},inplace=False)
df.iloc[10: 20]

    id_siswa jenis_kelamin  ...  nilai_keseluruhan  nilai
10    100010          Male  ...            77.0530      B
11    100011          Male  ...            62.9825      C
12    100012          Male  ...            92.3830      A
13    100013          Male  ...            49.0660      D
14    100014        Female  ...            48.2745      D
15    100015          Male  ...            74.2710      B
16    100016        Female  ...            62.9590      C
17    100017        Female  ...            55.2335      C
18    100018        Female  ...            61.0675      C
19    100019          Male  ...            81.7895      B

[10 rows x 14 columns]

### cek missing value

In [103]:
df.isna().sum()

id_siswa                0
jenis_kelamin           0
jam_belajar_per_hari    0
presentase_kehadiran    0
nilai_tugas             0
nilai_UTS               0
nilai_UAS               0
nilai_partisipasi       0
akses_internet          0
kelas_tambahan          0
pendidikan_orang_tua    0
jam_tidur               0
nilai_keseluruhan       0
nilai                   0
dtype: int64

### info data

In [104]:
df.info()
df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id_siswa              10000 non-null  int64
 1   jenis_kelamin         10000 non-null  str
 2   jam_belajar_per_hari  10000 non-null  float64
 3   presentase_kehadiran  10000 non-null  float64
 4   nilai_tugas           10000 non-null  float64
 5   nilai_UTS             10000 non-null  float64
 6   nilai_UAS             10000 non-null  float64
 7   nilai_partisipasi     10000 non-null  float64
 8   akses_internet        10000 non-null  str
 9   kelas_tambahan        10000 non-null  str
 10  pendidikan_orang_tua  10000 non-null  str
 11  jam_tidur             10000 non-null  float64
 12  nilai_keseluruhan     10000 non-null  float64
 13  nilai                 10000 non-null  str
dtypes: float64(8), int64(1), str(5)
memory usage: 1.1 MB

           id_siswa  jam_belajar_per_hari  ...     jam_tidur  nilai_keseluruhan
count   10000.00000          10000.000000  ...  10000.000000       10000.000000
mean   104999.50000              5.467825  ...      6.505165          63.826901
std      2886.89568              2.594134  ...      1.458246          10.230977
min    100000.00000              1.000000  ...      4.000000          33.263500
25%    102499.75000              3.220000  ...      5.220000          56.528125
50%    104999.50000              5.420000  ...      6.520000          63.780750
75%    107499.25000              7.740000  ...      7.792500          71.163125
max    109999.00000             10.000000  ...      9.000000          96.879500

[8 rows x 9 columns]

## encoding

In [105]:
df['jenis_kelamin'] = df['jenis_kelamin'].map({
    'Male' : 1,
    'Female': 0
})
df['akses_internet'] = df['akses_internet'].map({
    'Yes' : 1,
    'No' : 0
})
df['kelas_tambahan'] = df['kelas_tambahan'].map({
    'Yes' : 1,
    'No' : 0
})
df['pendidikan_orang_tua'] = df['pendidikan_orang_tua'].map({
    'PhD' : 3,
    'Master' : 2,
    'Bachelor' : 1,
    'High School' : 0
})
df['nilai'] = df['nilai'].map({
    'A' : 3,
    'B' : 2,
    'C' : 1,
    'D' : 0
})

df.head()

   id_siswa  jenis_kelamin  ...  nilai_keseluruhan  nilai
0    100000              1  ...            52.3480    0.0
1    100001              0  ...            53.9485    0.0
2    100002              1  ...            82.0375    2.0
3    100003              1  ...            66.4110    1.0
4    100004              1  ...            65.6005    1.0

[5 rows x 14 columns]

### cek missing value

In [118]:
df.isna().sum()

id_siswa                 0
jenis_kelamin            0
jam_belajar_per_hari     0
presentase_kehadiran     0
nilai_tugas              0
nilai_UTS                0
nilai_UAS                0
nilai_partisipasi        0
akses_internet           0
kelas_tambahan           0
pendidikan_orang_tua     0
jam_tidur                0
nilai_keseluruhan        0
nilai                   61
dtype: int64

### drop baris yang ada missing value

In [121]:
df = df.dropna(subset=['nilai'])
df.isna().sum()

id_siswa                0
jenis_kelamin           0
jam_belajar_per_hari    0
presentase_kehadiran    0
nilai_tugas             0
nilai_UTS               0
nilai_UAS               0
nilai_partisipasi       0
akses_internet          0
kelas_tambahan          0
pendidikan_orang_tua    0
jam_tidur               0
nilai_keseluruhan       0
nilai                   0
dtype: int64

## cek korelasi

In [68]:
corr = df.corr()
corr

                      id_siswa  jenis_kelamin  ...  nilai_keseluruhan     nilai
id_siswa              1.000000      -0.002756  ...           0.007520  0.006496
jenis_kelamin        -0.002756       1.000000  ...          -0.000307 -0.002321
jam_belajar_per_hari  0.011394      -0.004755  ...          -0.003651 -0.001383
presentase_kehadiran  0.002863      -0.000101  ...           0.148781  0.133164
nilai_tugas           0.009638      -0.006321  ...           0.396961  0.348972
nilai_UTS            -0.000074       0.007290  ...           0.528902  0.478320
nilai_UAS             0.006413      -0.001014  ...           0.689326  0.632948
nilai_partisipasi    -0.004485      -0.003857  ...           0.244067  0.213481
akses_internet       -0.002876       0.005169  ...           0.029078  0.022975
kelas_tambahan       -0.001979      -0.008847  ...           0.006219  0.002627
pendidikan_orang_tua  0.006117       0.003969  ...          -0.005177 -0.010603
jam_tidur            -0.015926      -0.004085  ...          -0.000551 -0.004652
nilai_keseluruhan     0.007520      -0.000307  ...           1.000000  0.918026
nilai                 0.006496      -0.002321  ...           0.918026  1.000000

[14 rows x 14 columns]

In [69]:
df.drop(columns='id_siswa')

      jenis_kelamin  jam_belajar_per_hari  ...  nilai_keseluruhan  nilai
0                 1                  4.54  ...            52.3480    0.0
1                 0                  5.26  ...            53.9485    0.0
2                 1                  8.69  ...            82.0375    2.0
3                 1                  4.06  ...            66.4110    1.0
4                 1                  8.83  ...            65.6005    1.0
...             ...                   ...  ...                ...    ...
9995              0                  6.86  ...            55.6720    1.0
9996              1                  2.60  ...            66.0930    1.0
9997              0                  1.46  ...            73.0355    2.0
9998              0                  7.15  ...            71.5400    2.0
9999              1                  3.26  ...            84.1005    2.0

[10000 rows x 13 columns]

### ekspor data

In [ ]:
try:    
    ekspor: pd.DataFrame = df.to_csv('../data/student_performance_clean.csv',index=False)
    print("ekspor file berhasil")
except Exception as e:
    print(f"ekspor gagal,{e}")